name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ğŸ”§
        run: yarn install
        working-directory: flint.ui

      - name: Lint ğŸ§
        run: yarn lint
        working-directory: flint.ui

      - name: Build ğŸ—ï¸
        run: yarn build
        working-directory: flint.ui

      - name: Storybook Build ğŸ¨
        run: yarn build-storybook -o ./storybook-build
        working-directory: flint.ui

      - name: Lint Dockerfile
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: ./flint.ui/Dockerfile
          error_level: 0
          output_format: tty
