name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master, 'feat/gcbm-simulation-editor']

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS âš¡ï¸
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache directory path ğŸ¤¯
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn ğŸ¥‚
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/flint.ui/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install ğŸ”§
        run: yarn install --frozen-lockfile
        working-directory: flint.ui

      - name: Lint ğŸ§
        run: yarn lint --no-fix --max-warnings 0
        working-directory: flint.ui

      - name: Storybook Build ğŸ¨
        run: yarn build-storybook -o ./storybook-build
        working-directory: flint.ui

      - name: Lint Dockerfile ğŸ³
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: ./flint.ui/Dockerfile
          error_level: 0
          output_format: tty
